[build]
  command = "pip install -r requirements.txt && python app.py"
  functions = "functions"
  publish = "/path/to/publish_directory"
  log = "debug"

[build.environment]
  PYTHON_VERSION = "3.8"

[[plugins]]
  package = "@netlify/plugin-functions-build"
