[build]
  command = "pip install -r requirements.txt && gunicorn -b 0.0.0.0:5000 app:app"
  functions = "functions/"
  publish = "."
[build]
  command = "python app.py"
  timeout = 900
  functions = "functions/"

[context.production]
  command = "pip install -r requirements.txt && python app.py"
  publish = "."
  timeout = 600  # 10 minut (możesz dostosować wartość)
