[build]
  command = "python app.py"
  publish = "."
[context.production]
  command = "pip install -r requirements.txt && python app.py"
  publish = "."
  timeout = 600  # 10 minut (możesz dostosować wartość)
