[build]
  command = "pip install -r requirements.txt && gunicorn -b 0.0.0.0:5000 app:app"
  functions = "functions/"
  publish = "."
  timeout = 900

[context.production]
  command = "pip install -r requirements.txt && python app.py"
  publish = "."
  timeout = 600
